[project]
name = "automl-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "pytest>=9.0.1",
    "pyyaml>=6.0.3",
    "uvicorn>=0.38.0",
]

[tool.uv]
package = true
